const CREATE_SESSION = "CREATE_SESSION";
const DELETE_SESSION = "DELETE_SESSION";
const DELETE_ALL_SESSIONS = "DELETE_ALL_SESSIONS";
const ADD_PHOTO_TO_SESSION = "ADD_PHOTO_TO_SESSION"
const INIT_STATE = "INIT_STATE"

export {
  CREATE_SESSION,
  DELETE_SESSION,
  DELETE_ALL_SESSIONS,
  ADD_PHOTO_TO_SESSION,
  INIT_STATE,
};
