const GET_ALL_SESSIONS = "GET_ALL_SESSIONS";
const CREATE_SESSION = "CREATE_SESSION";
const EDIT_SESSION = "EDIT_SESSION";
const DELETE_SESSION = "DELETE_SESSION";
const DELETE_ALL_SESSIONS = "DELETE_ALL_SESSIONS";

export {
  GET_ALL_SESSIONS,
  CREATE_SESSION,
  EDIT_SESSION,
  DELETE_SESSION,
  DELETE_ALL_SESSIONS,
};
